### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by indraastra** [pusherman/react-native-network-info#1]
Hi @pusherman, I was just wondering if you had any plans to implement Android support for this library. If not, would you mind if I took a crack at it and submitted a PR to avoid spawning a whole new library?

I've tested this out on iOS and it works perfectly by the way, so thanks!

**Comment by pusherman** [comment]
I would love a PR for Android support.  I currently do not have an Android phone to test things on so I do not have any plans on supporting it currently but would absolutely merge support in.

**Comment by indraastra** [comment]
Awesome, I'll start work on it tomorrow and keep you posted. It will likely require reorganizing the code into ios/ and android/ directories. I'm using this as reference:

https://github.com/tradle/react-native-udp

**Comment by pusherman** [comment]
Sounds great!  Good luck!

**Comment by indraastra** [comment]
Superseded by https://github.com/pusherman/react-native-network-info/pull/2, closing.
