### ISSUE TITLE
Build fails with 5.2.0 - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by jedashford** [pusherman/react-native-network-info#103]
Issue below is with 5.2.0, but not with 5.1.0 when building on iOS. Looks like it might be related to the addition of getGatewayIPAddress

Undefined symbols for architecture x86_64:
  "_getdefaultgateway", referenced from:
      -[RNNetworkInfo getGatewayIPAddress:rejecter:] in libreact-native-network-info.a(RNNetworkInfo.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by antonkulyk** [comment]
Experiencing the same problem. Looks like the problem has appeared in #98 
@parrotmac maybe you have an idea on a fix?

**Comment by gabrielrra** [comment]
Having the same issue here also

**Comment by umutcetinkaya** [comment]
i have same problem. Does anyone have a solution?

**Comment by antonkulyk** [comment]
This pull request looks like a fix #106

**Comment by SkyPeer** [comment]
> This pull request looks like a fix #106

Awesome! 
thank you very much!

**Comment by pusherman** [comment]
I just confirmed it does, will be releasing an update by EOD.

**Comment by pusherman** [comment]
Should be fixed in 5.2.1.
