### ISSUE TITLE
ios 13 Unable to get wifi ssid

### ISSUE THREAD

**Issue by JayChiuTW** [pusherman/react-native-network-info#105]
After the mobile phone has been updated to the first version, the SSID of the WIFI can't be obtained normally. Every time it is returned to Wi-Fi, how to solve the problem?

**Comment by nik-garg** [comment]
> After the mobile phone has been updated to the first version, the SSID of the WIFI can't be obtained normally. Every time it is returned to Wi-Fi, how to solve the problem?

You need to ask for user location for getting wifi-ssid in ios 13.
Use react native geolocation (https://facebook.github.io/react-native/docs/geolocation.html).
1. Add the permission in Info.plist ( key :  "NSLocationWhenInUseUsageDescription" )
2. Add a call for requesting user permission to access location ( function to call : geolocation.requestAuthorization() )

**Comment by redwind** [comment]
it's work only on iphone 6s, ip 6splus, on ip7, wifi ssid still return nill althought location permission is Always. Anyone check this on ip 7 ? Thanks !

**Comment by memelie** [comment]
Same problem on iPhone6S. I have added Geolocation and asked for permissions which is granted.

**Comment by memelie** [comment]
Finally got it to work by updating iOS13 to the very last release :)

**Comment by JayChiuTW** [comment]
> > After the mobile phone has been updated to the first version, the SSID of the WIFI can't be obtained normally. Every time it is returned to Wi-Fi, how to solve the problem?
> 
> You need to ask for user location for getting wifi-ssid in ios 13.
> Use react native geolocation (https://facebook.github.io/react-native/docs/geolocation.html).
> 
> 1. Add the permission in Info.plist ( key :  "NSLocationWhenInUseUsageDescription" )
> 2. Add a call for requesting user permission to access location ( function to call : geolocation.requestAuthorization() )

I did what you said. I successfully got SSID on the IOS13 system. Thank you very much.

**Comment by JayChiuTW** [comment]
@nik-garg I did what you said. I successfully got SSID on the IOS13 system. Thank you very much.

**Comment by daihieptn97** [comment]
I did as you said and it doesn't run into the console.log function
```js
Geolocation.requestAuthorization();

          NetworkInfo.getSSID(ssid => {
              console.log(ssid); // not woking
              NetworkInfo.getBSSID(bssid => {
                  if (bssid != "error") {
                      self.setState({ bssidWifi: bssid });
                  }
                  self._getListWifi(ssid, bssid);
              });

              if (ssid != "error") {
                  self.setState({ ssidWifi: ssid });
              } else {
                  Toast.show({
                      text: "Bạn chưa kết nối tới wifi",
                      type: "warning"
                  });
              }
          });
```

Thanks you!

**Comment by dmwallace** [comment]
@daihieptn97 it looks like the NetworkInfo.getSSID function now returns a promise rather than taking a callback argument so your code should now be like: 

`NetworkInfo.getSSID().then(ssid => {…})`

this caught me out too

**Comment by daihieptn97** [comment]
> @daihieptn97 it looks like the NetworkInfo.getSSID function now returns a promise rather than taking a callback argument so your code should now be like:
> 
> `NetworkInfo.getSSID().then(ssid => {…})`
> 
> or
> 
> `let ssid = await NetworkInfo.getSSID()`
> 
> this caught me out too

thanks you so much !

**Comment by shengliZh** [comment]
Why ssid is undefined?

**Comment by JayChiuTW** [comment]
> let ssid = await NetworkInfo.getSSID();
> or
> NetworkInfo.getSSID().then(ssid => {…})
> ssid return undefined, why?

**Comment by JayChiuTW** [comment]
> let ssid = await NetworkInfo.getSSID();
> or
> NetworkInfo.getSSID().then(ssid => {…})
> ssid return undefined, why?

**Comment by JayChiuTW** [comment]
@shengliZh Add the permission in Info.plist ( key : "NSLocationWhenInUseUsageDescription" )

**Comment by shengliZh** [comment]
![image](https://user-images.githubusercontent.com/25652977/67823030-77cae900-fafc-11e9-8e6f-fe07d0ba1f31.png)
![image](https://user-images.githubusercontent.com/25652977/67823058-9204c700-fafc-11e9-858a-9190a4198c67.png)
![image](https://user-images.githubusercontent.com/25652977/67823070-a34dd380-fafc-11e9-9a97-18c403fca6bd.png)
I have added this permission, but still get ssid undefined, what should I do?@JayChiuTW

**Comment by nik-garg** [comment]
> ![image](https://user-images.githubusercontent.com/25652977/67823030-77cae900-fafc-11e9-8e6f-fe07d0ba1f31.png)
> ![image](https://user-images.githubusercontent.com/25652977/67823058-9204c700-fafc-11e9-858a-9190a4198c67.png)
> ![image](https://user-images.githubusercontent.com/25652977/67823070-a34dd380-fafc-11e9-9a97-18c403fca6bd.png)
> I have added this permission, but still get ssid undefined, what should I do?@JayChiuTW

This won't work in a virtual device. Test this in an actual device.

**Comment by joshbg2k** [comment]
I've added the permission in info.plist, granted authorization, and `getSSID()` returns undefined for me.

iPhone 7 Plus
iOS 13.2
React Native 0.55.4
React Native Network Info 5.2.1

**Comment by memelie** [comment]
According to this post : https://stackoverflow.com/questions/58072820/how-to-get-current-network-information-for-a-given-network-interface-on-ios-13
You need to reboot the device. Worked for me.
Not sure it has to do with the package, more with iOS13 itself

**Comment by joshbg2k** [comment]
@memelie that worked, thanks!
