### ISSUE TITLE
ios run error in the simulator

### ISSUE THREAD

**Issue by sunny20131314** [pusherman/react-native-network-info#12]
Hello！

<React/RCTBridge.h> is not found.

node_modules/react-native-network-info/ios/RNNetworkInfo.h:10:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^
1 error generated.

    "react": "^15.4.1",
    "react-native": "^0.39.2",
    "react-native-network-info": "^1.0.0"

**Comment by pusherman** [comment]
The 1.0 release requires react-native .40 or above.  Can you try to update your react-native and see if the problem persist?  

Alternatively you can downgrade reactive-native-network-info to 0.2.0

**Comment by sunny20131314** [comment]
thanks!
it's works when i downgrade reactive-native-network-info to 0.2.0~~~
