### ISSUE TITLE
Error Installing library

### ISSUE THREAD

**Issue by jose920405** [pusherman/react-native-network-info#17]
`****/node_modules/react-native-network-info/ios/RNNetworkInfo.h:10:9: 'React/RCTBridge.h' file not found`

This is my config.

![screen shot 2017-03-14 at 9 45 04 am](https://cloud.githubusercontent.com/assets/12536184/23906096/0a76963e-089b-11e7-876a-57d5b4be9265.png)
-------
![screen shot 2017-03-14 at 9 45 29 am](https://cloud.githubusercontent.com/assets/12536184/23906101/0bbadaa0-089b-11e7-9bcf-5b887d37fe56.png)
-------
![screen shot 2017-03-14 at 9 45 44 am](https://cloud.githubusercontent.com/assets/12536184/23906105/0d9d6fe0-089b-11e7-8173-d9b27700e156.png)
-------

**Comment by pusherman** [comment]
The 1.0 release requires react-native .40 or above. Can you try to update your react-native and see if the problem persist?

Alternatively you can downgrade reactive-native-network-info to 0.2.0

**Comment by pusherman** [comment]
I'll assume this is resolved by upgrading react native. Let me know if not.
