### ISSUE TITLE
Android installation

### ISSUE THREAD

**Issue by jagi** [pusherman/react-native-network-info#18]
Hi, in docs it says that I have to modify the `MainActivity.java` file. But mine looks a little bit different:

```java
package com.myapp;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyApp";
    }
}
```

So how can I install it?

I'm using ReactNative 0.41

**Comment by MattyK14** [comment]
Hey, just solved this issue myself.

Add the following to your `MainApplication.java`

`import com.pusherman.networkinfo.RNNetworkInfoPackage;`

```
  @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
              ...
              new RNNetworkInfoPackage(),
              ...
      );
    }
```

**Comment by jagi** [comment]
OK thank! I will try that

**Comment by pusherman** [comment]
thanks @MattyK14 

@jagi let me know if it works.  I'm working on updating the documentation now for the current versions of reactive native and android studio.

**Comment by jagi** [comment]
@MattyK14 @pusherman yes it works. Thanks!
