### ISSUE TITLE
ip = "error"

### ISSUE THREAD

**Issue by mgscreativa** [pusherman/react-native-network-info#20]
Hi! I can't get the current device IP on iOS simulator. I'm getting IP = error.

I'm currently tehtering the phone internet connection to my mac because I'm having issues with my broadband provider, maybe that's the issue.

Just let me know if I can test something.

Thanks!

**Comment by pusherman** [comment]
Unfortunately the simulator does not provide the IP address.  You'll only be able to get it on the actual device.
