### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by L3V147H4N** [pusherman/react-native-network-info#26]
do you have any future plans regarding this package?
Maybe getBSSID (endpoint) for ex?
I suggest BSSID because is usually very useful when working in some environment where there are lots of endpoints but all have the same SSID

**Comment by pusherman** [comment]
That's a great idea. I'll look in to it.  Feel free to offer a PR if you have code handy. 

Thanks for the suggestion!

**Comment by pusherman** [comment]
@L3V147H4N - I have just pushed up code that allows you to get the BSSID in both iOS and Android.  I've tested it on iOS but, unfortunately, I do not have an Android device to test it on (the SSID and BSSID feature does not work on the simulator).   

Could you give it a test on whatever OS you are working on when you have a moment?  I haven't tagged the feature in a release yet so you'll have to pull from master directly in your package.json.

**Comment by L3V147H4N** [comment]
Sure, I'm working with this package today so I'll give it a test 👍

**Comment by L3V147H4N** [comment]
Just tested with latest RN (0.43.4) in my Xperia Z3+ with android 7.0 and it works :3 ready to publish to npm :) 👍

**Comment by L3V147H4N** [comment]
once is one npm you can close this issue, many thanks for the quick reply and codding :)

**Comment by pusherman** [comment]
npm updated, thanks again for the suggestion!
