### ISSUE TITLE
Don't switch to import

### ISSUE THREAD

**Issue by jbrodriguez** [pusherman/react-native-network-info#27]
Please don't do a92b6e4fc530c071496523e4d725ed3de27944bd.

Even if you pre-'babelify' before pushing to npm, it will cause trouble for forks that need to npm/yarn install/add directly from github.

**Comment by pusherman** [comment]
Not sure what you mean.  React Native ships with Babel and ES6 modules are an [enabled transformation](https://facebook.github.io/react-native/docs/javascript-environment.html#javascript-syntax-transformers).

Also, the React Native docs recommend using ES6 modules in [their examples](https://facebook.github.io/react-native/docs/native-modules-ios.html).

**Comment by jbrodriguez** [comment]
You're right.

I had the issue when running ava tests and importing my fork of the library.

I had to replace the import with a require, since ava didn't recognize the es6 features.

I'll make some other checks to look for a workaround.
