### ISSUE TITLE
getSSID() and getBSSID() seem not work

### ISSUE THREAD

**Issue by kaikyle7997** [pusherman/react-native-network-info#30]
Hello,
First, appreciate that you put the contribution to the RN-related network development.

I am now attempting to experiment this package in my project but it seems I occurred non-expected results when using them, i.e., getSSID() and getBSSID(). Both Android and iOS simulators I run on always give me error message. Is there any version requirements like for RN or others? Please help me let it work, so thanks to you in advance. ;)

Below key snippet are placed in component's onPress() event.
```
// Get SSID
NetworkInfo.getSSID(ssid => {
  console.log(ssid);
});

// Get BSSID
NetworkInfo.getBSSID(ssid => {
  console.log(ssid);
});
```
After the component is pressed, get two 'error' in my debug console.
```
// for iOS
error
error

// for Android
<unknown ssid>
null
```

**Comment by kaikyle7997** [comment]
Oh. I found this issue https://github.com/pusherman/react-native-network-info/issues/5, try it on later, thank you so much. :)

**Comment by pusherman** [comment]
Awesome. Let me know if you have problems on the device.
