### ISSUE TITLE
getSSID not working on IOS device (real)

### ISSUE THREAD

**Issue by manuTro** [pusherman/react-native-network-info#33]
Hi, 
I cannot detect SSID name on the real Iphone. 
I've this error

> #object[TypeError TypeError: undefined is not an object (evaluating 'RNNetworkInfo.getSSID')]

No problem by using an android device.

 IOS 10.3.2
"react": "^16.0.0-alpha.6",
 "react-native": "^0.44.0"
"react-native-network-info": "^2.0.0"

**Comment by pusherman** [comment]
I'm traveling but will check it out when I return home next week.  In the mean time, have you tried with the latest version of the library 3.0?

**Comment by manuTro** [comment]
I cannot try because I'm using react-native 0.44.0 and now I cannot upgrade because I'm writing in clojurescript (and I'm using another library that requires me to use react-native 0.44) ^^'
Let me know when you'll check :) thx

**Comment by seriiix** [comment]
I'm using react-native 0.49 and its not working for me as well

**Comment by manuTro** [comment]
There is no fix for  react-native 0.44.0?

**Comment by steele-cjf** [comment]
hi， what solution？
