### ISSUE TITLE
NetworkInfo functions always return error on IOS

### ISSUE THREAD

**Issue by sircEUNHO** [pusherman/react-native-network-info#34]
I am using IOS 11.0 Simulator and XCODE 9.0. 
My React Native version is `0.49.3`, react-native-network-info version is `3.0.0`. 

This is my code  on my app: 
```
import { NetworkInfo } from 'react-native-network-info';


  componentDidMount() {
    NetworkInfo.getSSID((ip) => {
        alert(ip);
    });
  }
```

what it show is: 
![screen shot 2017-10-14 at 11 58 20 pm](https://user-images.githubusercontent.com/30286632/31577134-a1d197ec-b13b-11e7-9a64-a555f47b3b19.png)

How can i fix this? I installed it according to the docs and it doesn't have any building error?

**Comment by pusherman** [comment]
Unfortunately getting the SSID does not work in the iOS simulator. 
 It should work on the real device though.  Please open a new issue if it doesn't.

https://github.com/pusherman/react-native-network-info/issues/5
