### ISSUE TITLE
Compilation fail due to RNNetworkInfoPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by stanleycyang** [pusherman/react-native-network-info#35]
react-native-network-info/android/src/main/java/com/pusherman/networkinfo/RNNetworkInfoPackage.java:14: error: RNNetworkInfoPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public final class RNNetworkInfoPackage implements ReactPackage {
             ^
1 error
:react-native-network-info:compileReleaseJavaWithJavac FAILED

**Comment by DanielMSchmidt** [comment]
This error may occur if you use a RN version 0.46 or lower with version 3.X of this library. You need to switch to 2.X as stated in the Readme
