### ISSUE TITLE
IPv4 ios?

### ISSUE THREAD

**Issue by sibelius** [pusherman/react-native-network-info#39]

**Comment by pusherman** [comment]
can you provide a little more info?

**Comment by sibelius** [comment]
why this

```
// Get IPv4 IP (Android Only)
NetworkInfo.getIPV4Address(ipv4 => {
  console.log(ipv4);
});
```

only works on android?

**Comment by pusherman** [comment]
ah, i haven't looked in to checking for ipv4 directly in iOS yet.  That code was included as a PR by someone else and they only did the Android side for now.

**Comment by acb** [comment]
@pusherman any plans to publish a new version on npm now that https://github.com/pusherman/react-native-network-info/pull/45 was merged?  Would be great to have `getIPV4Address` parity on Android and iOS.

**Comment by pusherman** [comment]
@acb sure, I'll try to have it out by the end of the week.  I am working on a more comprehensive solution but I'll push out this change as is until I can get a bigger one in place.

**Comment by pusherman** [comment]
@acb - i went ahead and did the release.  It seems to be on NPM but I keep getting a 504 on publish.  Seems as though npm is having issues and has been for a while https://github.com/npm/npm/issues/19871

I'll keep an eye on it.

**Comment by acb** [comment]
@pusherman thanks! npm lists the latest version as 3.1.0 so it looks like it went through.  I'll give it a whirl later tonight!
