### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNNetworkInfo.getSSID')

### ISSUE THREAD

**Issue by cerqueirapt** [pusherman/react-native-network-info#40]
Hello!

I'm trying to use this library on an Android smartphone (not emulator) and I can't really get any information from it. I believe all the setup has been done right, so it should be working.

What happens is that when I try to use any `NetworkInfo` methods it always says:

```
TypeError: undefined is not an object (evaluating 'RNNetworkInfo.getSSID')

This error is located at:
    in App (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
- node_modules/react-native-network-info/NetworkInfo.js:8:18 in getSSID
* App.js:21:24 in render
```

I'm not sure what can be wrong with this... This is a clear installation with `create-react-native-app` and after `react-native eject`. Also worth noting that I'm using [Expo](http://expo.io/) within the project...

Any tips on what's happening? If you need more info, just let me know exactly what info.

Thanks in advance!

**Comment by Catpants** [comment]
What version of react native are you on? I am getting the same error and I am on react native v0.50.3. The latest supported version of this package is 0.47.

**Comment by pusherman** [comment]
@und0ck3d what version of the library and react native are you using?

**Comment by Chatharaju** [comment]
I have react-native version 50.4, and I have installed the library version 3.1.0. Still shows me the same error

**Comment by pusherman** [comment]
Can you paste some of your code?  Specifically your import and when you are calling getSSID

**Comment by Chatharaju** [comment]
Here you go:
import { NetworkInfo } from 'react-native-network-info';
componentWillMount () {
     this.getSSID();
  }
  getSSID() {
    NetworkInfo.getSSID(ssid => {
        this.setState({
         wifiSSID: ssid,
       });
     });
   }

**Comment by pusherman** [comment]
Oh, sorry, I missed the part in your original post where it says you are using Expo.  Native modules won't work that way.

Set up a new project and run `react-native link` to link the library.

**Comment by pusherman** [comment]
so it was-- well, that is his problem :)

Not sure about yours.  I have tested it with a native android device on 50.4 and it works okay.  Are you sure the library is linked?

**Comment by pusherman** [comment]
@Chatharaju can you give it a shot with 3.2.0?  Make sure you do a fresh install on a new project and run `react-native link`

**Comment by yangmengsen** [comment]
Under ios, "Cannot read property 'getIPAddress' of undefined" devices and react-native are the latest versions.

**Comment by yangmengsen** [comment]
Under ios, "Cannot read property 'getIPAddress' of undefined" devices and react-native are the latest versions.

**Comment by Chatharaju** [comment]
I do have 3.2.2 installed and still having issues with android. iOS seems to be working fine. Think it has to do with the linking on android.

**Comment by Bobozee** [comment]
Do not forget to link and then RE-BUILD the project!

**Comment by psalmeight** [comment]
Had issues with `NetworkInfo.getIPAddress` not being recognized. Turns out that `react-native link react-native-network-info` did not work. According to their documentation, if `react-native link` fails, then link manually.

![image](https://user-images.githubusercontent.com/37855474/40790025-63c35b44-6526-11e8-82f6-fce11f23f818.png)

**Comment by nickwanhere** [comment]
Try this https://github.com/pusherman/react-native-network-info/issues/53#issuecomment-395073927

**Comment by qayyummdnoor** [comment]
is it solve yet? i also had done react native link and following all the steps but same error will show up.
