### ISSUE TITLE
[HELP REQUIRED]  Method getIPAddress() gives the local IP address

### ISSUE THREAD

**Issue by rajat-np** [pusherman/react-native-network-info#42]
Method **getIPAddress()** gives the **local IP** address, how can I get the **external IP** address.

**Comment by pusherman** [comment]
this library only provides the local ip (currently).  You will need to use some other method to get the external ip address.

**Comment by rajat-np** [comment]
I managed to get the external IP using an API. Maybe I can create a PR with this added functionality i.e to get the external IP within this module.

**Comment by pusherman** [comment]
sure, i'd love to check out a PR

**Comment by rajat-np** [comment]
@pusherman , I think there is no need for the above PR since external IP can be made available by a simple GET to this [https://api.ipify.org/](url) .

**Comment by rajat-np** [comment]
@pusherman , I think there is no need for the above PR since external IP can be made available by a simple GET to [https://api.ipify.org](url) .

**Comment by pusherman** [comment]
@rajat-np yeah, i agree-- thanks!
