### ISSUE TITLE
Problems getting SSID to work in Simulator

### ISSUE THREAD

**Issue by mckn** [pusherman/react-native-network-info#5]
Hello,

I have problems getting SSID when I'm running the XCode iOS simulator. I am running it as a iphone 6S with iOS 9.2. No interfaces is found and 'error' is returned. Should it be able to work in the simulator or what can I have made wrong? I can get the IP without any problems.

thanks!

**Comment by pusherman** [comment]
It actually will not work in the simulator.  The simulator doesn't support interfaces unfortunately.  It should work fine when running on the device though.

**Comment by mckn** [comment]
Ah, okay! Then I know why it didnt work in the simulator.

**Comment by MattyK14** [comment]
Is there any code to prevent the crash on simulators but that it still runs on a real device?

**Comment by pusherman** [comment]
does it crash the simulator or is it just not working in the simulator?

**Comment by MattyK14** [comment]
It crashes the Android & iOS simulators. I've avoided it with a try and catch.
