### ISSUE TITLE
node_modules\react-native-network-info\android\src\main\java\com\pusherman\networkinfo--- run gradlew assembleRelease to build APK error

### ISSUE THREAD

**Issue by skylingfly** [pusherman/react-native-network-info#50]
when you run gradlew assembleRelease to build APK, there will be an error as below:

node_modules\react-native-network-info\android\src\main\java\com\pusherman\networkinfo\RNNetworkInfoPackage.java:26: 错误: 方法不会覆盖或实现超类型的方法
    @Override

**Comment by skylingfly** [comment]
you can commented code as below:
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return new ArrayList<>();
    }

**Comment by sebirdman** [comment]
Yup, for this version we should not have this class: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

not sure why this got added back but it makes any update past 3.1.0 break android builds.

**Comment by pusherman** [comment]
Thanks guys!  Just pushed out a new release that should resolve it.
