### ISSUE TITLE
China google……

### ISSUE THREAD

**Issue by fanlide** [pusherman/react-native-network-info#52]
![tim 20180413120206](https://user-images.githubusercontent.com/20534139/38716310-967443da-3f12-11e8-9ad0-478994793d91.png)

**Comment by pusherman** [comment]
what version of gradle are you on?  The latest version the library requires at gradle 3.

**Comment by fanlide** [comment]
my gradle 3.3.I think so is China can't access Google

**Comment by fanlide** [comment]
@appaaaa What version of gradle have you updated?

**Comment by fanlide** [comment]
In China you need to modify the `node_modules/react-native-network-info/android/build.gradle`

```java
    repositories {
        jcenter()
        google()
    }
```
**replace**

``` java
   repositories {
        jcenter()
        maven{ url 'http://maven.aliyun.com/nexus/service/local/repositories/google/content/'}
    }
```

**Comment by goleador0322** [comment]
OMG, you are god.
In Japan, the same solution is valid ......

**Comment by Mscynol** [comment]
I have the same problem!!!!
![1](https://user-images.githubusercontent.com/13941582/43507197-fe1733de-959e-11e8-9da2-5b0fa7acf2af.png)
![2](https://user-images.githubusercontent.com/13941582/43507210-06548dd0-959f-11e8-9be7-956930d8bace.png)

**Comment by Mscynol** [comment]
I have solved it ！

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

repositories {
    jcenter()
    maven {
          url 'https://maven.google.com/'
          name 'Google'
    }
}

**Comment by pusherman** [comment]
using  `google()`  is a shortcut to Google's maven repo and was introduced in Gradle 4.  If you are on Gradle 3 or below you will need to change it to the code above.
