### ISSUE TITLE
error getipaddress in ios

### ISSUE THREAD

**Issue by gustavomo** [pusherman/react-native-network-info#57]
function return error, where execute in ios

**Comment by williamcabrera4** [comment]
The same happens to me trying with `getSSID`
```
iOS: 11.4
react-native-cli: 2.0.1
react-native: 0.50.4
react-native-network-info": "^3.2.2",
```

**Comment by pusherman** [comment]
@williamcabrera4 do you only have an issue with the `getSSID` or is `getIPAddress` not working for you as well?  Is this in the simulator or on an actual device?

**Comment by pusherman** [comment]
@gustavomo in the simulator or on an actual device?

**Comment by gustavomo** [comment]
on device

**Comment by Kerrin631** [comment]
I am having the same issue. This works fine on android but it returns error on ios

**Comment by Kerrin631** [comment]
on the ios simulator that runs when i use react-native run-ios I get the error "Cannot read property 'getIPAddress' of undefined". When I run through Xcode this error does not show up but getIPAddress returns error. I am experiencing no issues through Android. 

I user react-native link which installed properly on android but not on iOS so I manually followed the steps for the iOS installation.

Does anyone know why this is happening?

**Comment by sean-obrien** [comment]
Did anyone find a solve for this?  I've updated the project's Build Capabilities to include Access Wifi Information as well - no change... getIPAddress returns "error"

**Comment by th0r0nd0r** [comment]
I'm experiencing this with:
RN `0.56.0`
iOS `12.2`
running on iPhone 6 simulator

I'm logging the functions just before invocation and they are defined. Then when I try to call them either with async/await or by logging the response in a `.then`, I get the error:
`TypeError: Cannot read property 'getIPV4Address' of undefined`.
I get this error for any function I try to invoke. I've confirmed linking and rebuilt the app. Not sure what I'm doing wrong here, any help would be appreciated

**Comment by th0r0nd0r** [comment]
I'm also seeing this issue on a real device, iPhone 6 running iOS 12.3.1

**Comment by th0r0nd0r** [comment]
update for anyone still searching:

even though the `react-native link react-native-network-info` registered as successful in the terminal, I still had to follow the manual iOS linking steps.

**Comment by syedamirali14** [comment]
does anyone have solution for this?

**Comment by syedamirali14** [comment]
i get the solution 

    NetworkInfo.getIPV4Address().then(ipAddress => {
      console.log('ip address', ipAddress);
      this._continuePayment(ipAddress);
    });

**Comment by boblitex** [comment]
no love for this library at all? did you all find alternatives? these same issues still persist here now 😞 

looking to help here. is the Author(s) still active?

**Comment by cwilsn** [comment]
No, this package is no longer maintained.  Check out https://github.com/react-native-netinfo/react-native-netinfo#netinfostate

**Comment by boblitex** [comment]
> No, this package is no longer maintained. Check out https://github.com/react-native-netinfo/react-native-netinfo#netinfostate

okay, thank you @pusherman, already used that one before even finding this package. was trying to get a way to get the gateway IP address, not sure the net info package has that
