### ISSUE TITLE
Package is overweighted

### ISSUE THREAD

**Issue by Nabellaleen** [pusherman/react-native-network-info#71]
Hi,

After a npm install of your package, the directory size is 61M, mostly due to android build directory, embedding stuff which should not be commited

You should clean that, it's totally useless and horrible for users :)

**Comment by Nabellaleen** [comment]
Tips to resolve the problem : https://github.com/react-native-community/react-native-camera/issues/2000#issuecomment-447328777

**Comment by pusherman** [comment]
resolved in 5.0.0, thanks!
