### ISSUE TITLE
does not return valid ip address, ip start from 10. instead of 192. Also getBroadcast() method throw error

### ISSUE THREAD

**Issue by Sanjeet1** [pusherman/react-native-network-info#72]

**Comment by Sanjeet1** [comment]
Too many error.

**Comment by pusherman** [comment]
Can you provide more info?   

What OS are you using?  
What IP are you getting?  
What IP do you expect?

**Comment by tony-ward** [comment]
hey, I seem to be getting this same issue.
Android 8.1 on Oppo Real Me.
IP address is 192.168.0.x as shown by mobile, but getIpV4Address is showing 10.x.x.x.
Should be 192.168.0.x

**Comment by Rapsssito** [comment]
The function `getIpV4Address` iterates through all **available** device interfaces and returns the last **cached** valid IP. If your mobile has been connected to the cellular network recently, that will be the IP resolved (Ex: 10.xxx...).

This is why I created a new function **`getWIFIIPV4Address`**, (Pull Request https://github.com/pusherman/react-native-network-info/pull/99) which is still waiting for approval.
