### ISSUE TITLE
getSSID Android 8.1 'unknow'. Help me please!

### ISSUE THREAD

**Issue by PhuongNguyenETIT** [pusherman/react-native-network-info#76]

**Comment by erickmonteiro** [comment]
+1

**Comment by MarcoTerzoloGit** [comment]
Hi People, the issue is related to new Android 8.1 security patch. This means you should ask RUNTIME permission to user for FINE_LOCATION or COARSE_LOCATION to get the SSID

**Comment by PhuongNguyenETIT** [comment]
> Hi People, the issue is related to new Android 8.1 security patch. This means you should ask RUNTIME permission to user for FINE_LOCATION or COARSE_LOCATION to get the SSID

Thank you. Can you guide me?

**Comment by PhuongNguyenETIT** [comment]
Thank you, @MarcoTerzoloGit. I have done it.
