### ISSUE TITLE
Null is not an object (evaluating RNNetworkinfo.getIPAddress)

### ISSUE THREAD

**Issue by bartoszboruta** [pusherman/react-native-network-info#83]
![image](https://user-images.githubusercontent.com/17254885/52750419-78623480-2fec-11e9-9c09-92b12bc3e89f.png)
Hi,
I have a problem with use that package.
Linked without problems.

Dependencies:
"react-native": "0.58.3",
"react": "16.6.3",

App created with react-native init.

**Comment by shuffledex** [comment]
what was the solution?  I have the same issue

**Comment by inf3rnus** [comment]
I too am interested in the solution? Why do you keep closing issues without providing a solution? I get that you've helped us immensely by making this plugin in the first place, but that's pretty frustrating.

**Comment by pusherman** [comment]
@inf3rnus - it's not me that's closing the issue.  You can see in the thread above that the user that created the issue closed it, then reopened it, then closed it again.

If you are having the same issue, please feel free to open a new issue and provide a little more info than this user did.  What OS, Android/iOS, how are you linking the library, example of your code, etc.

**Comment by shuffledex** [comment]
I found the solution last day... We need to use the callback version instead await... If you look at *.java file, there are the old version methods with callback as required param.
The readme file is actually wrong, I don't know why but Android version is out of date.
Hope it works!

**Comment by pusherman** [comment]
ah, yes, thanks @shuffledex -- the readme is what is currently in master and that version uses async/await.  I need to release a 5.0 version that will switch from using callbacks.  I'll get the readme updated so it shows how to use both the < 5 version and >=5 version.

Thank you!
