### ISSUE TITLE
Cant assign result to variable

### ISSUE THREAD

**Issue by stardothosting** [pusherman/react-native-network-info#85]
I hope I'm not missing something but the following doesnt work 👍 

`var local_ip = NetworkInfo.getIPV4Address(ipv4 => { return ipv4; });
alert(local_ip);
`

The local_ip variable is undefined when trying to access. Am I missing something?

**Comment by pusherman** [comment]
You can't return a value from an async call like that.  Version 5.0.0 uses promises, so the syntax would be different (check out the readme) but for the <5.0.0...

```
NetworkInfo.getIPAddress(ipv4 => {
  var local_ip = ipv4; 
  alert(local_ip);
});
```
