### ISSUE TITLE
Published npm package has android build intermediates

### ISSUE THREAD

**Issue by rye** [pusherman/react-native-network-info#87]
I noticed that this package is one of the largest in my installed `node_modules` bundle.  Investigating further, I found that one of the largest dirs is `react-native-network-info/android`, whose largest subdir is `android/build`.

I don't think those should be included, and in fact they are ignored by the `.gitignore`.  It seems that they have been published regardless, and I do not think this should be the case.

You can verify this currently via `npm view react-native-network-info dist.tarball 2>/dev/null | xargs wget; tar tvzf *.tgz`.  I did not include this in the issue because there are 1797 lines of output, 1756 of which are `android/build` files.

**Comment by rye** [comment]
(This could be because a `.npmignore` is present on the machine that is publishing.  The `.gitignore` has a rule to ignore `build/`, which in `npm`'s default behavior should be applied to `android/build`, but does not seem to be.)

**Comment by pusherman** [comment]
resolved in v5.0.0.  Thanks!
