### ISSUE TITLE
feature request - signal strength

### ISSUE THREAD

**Issue by russellmorgan** [pusherman/react-native-network-info#88]
_Sorry for making this an "issue" but I couldn't find any other way to make contact..._

Is there method to check the signal strength?
Something like this: https://developer.apple.com/documentation/networkextension/nehotspotnetwork/1618923-signalstrength

**Comment by pusherman** [comment]
That is currently not available.  I haven't thought about adding that in but it's not a bad idea.  I'll leave this open and see if I can find a way to add it in for both iOS and Android.

**Comment by russellmorgan** [comment]
Awesome, thanks for getting back to me. I'm currently trying to figure out how to get the strength for a prototype I'm working on and I'm hitting quite a road block. Any advice you have on the subject would be welcome, happy to fork and contribute to repo if I make a breakthrough.

**Comment by pusherman** [comment]
I would start here: https://stackoverflow.com/questions/32970711/is-it-possible-to-get-wifi-signal-strength-in-ios-9

**Comment by russellmorgan** [comment]
Thanks man! It's what I was afraid of, you need to go for a second approval with Apple to register the app as a hotspot helper. (not a problem with Android)

**Comment by Rapsssito** [comment]
@russellmorgan you should check this: https://github.com/react-native-community/react-native-netinfo#netinfostate

**Comment by russellmorgan** [comment]
@Rapsssito That is exactly what I needed, thanks so much for the link!
