### ISSUE TITLE
react-native-network-info@4.0.1 :: SdkVersion 26 too old，can you publish a new version

### ISSUE THREAD

**Issue by MaShizhen** [pusherman/react-native-network-info#92]
node_modules/react-native-network-info/android/build.gradle

```code
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
```

hi,  ***SdkVersion*** is too old。can you publish a new version of npm?

**Comment by pusherman** [comment]
What version are you looking for?  Would 28 work?

```
android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
```

**Comment by MaShizhen** [comment]
yes！28 is ok. thank you！




------------------ 原始邮件 ------------------
发件人: "Corey Wilson"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 晚上9:08
收件人: "pusherman/react-native-network-info"<react-native-network-info@noreply.github.com>; 
抄送: "马士振"<2473872761@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pusherman/react-native-network-info] react-native-network-info@4.0.1 :: SdkVersion 26 too old，can you publish a new version (#92)




What version are you looking for?  Would 28 work?
 android {     compileSdkVersion 28     buildToolsVersion "28.0.3"

**Comment by MaShizhen** [comment]
hi，please publish a new version on npm
thank you
