### ISSUE TITLE
about  androidx.annotation.NonNull

### ISSUE THREAD

**Issue by MaShizhen** [pusherman/react-native-network-info#93]
Thank you very much for releasing the new package on NPM.

But now I have some other problems, [androidx.annotation.NonNull](https://github.com/pusherman/react-native-network-info/blob/master/android/src/main/java/com/pusherman/networkinfo/RNNetworkInfo.java#L6) throw out error

![image](https://user-images.githubusercontent.com/31983261/58458651-53896b80-815c-11e9-9bfb-c0f5208c3b8c.png)

I don't think [this import](https://github.com/pusherman/react-native-network-info/blob/master/android/src/main/java/com/pusherman/networkinfo/RNNetworkInfo.java#L6) is used. Can you remove it?

**Comment by pusherman** [comment]
I'm traveling for the next week so I don't have an android device to test out but if someone can verify removing that import fixes the issue for you guys I can deploy the fix.

**Comment by GuillermoRivera** [comment]
Sure, give me a moment and I can test on my devices. Let you know how it goes. Thanks @pusherman

**Comment by GuillermoRivera** [comment]
Hi, I already tested on my Android device and it worked.
I just removed this line from the code https://github.com/pusherman/react-native-network-info/blob/v5.0.0/android/src/main/java/com/pusherman/networkinfo/RNNetworkInfo.java#L6

**Comment by pusherman** [comment]
Removed in v5.0.1  

Thanks guys!
